name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Deploy
      working-directory: flask
      env:
        HOME_URL: ${{ secrets.HOME_URL }}
        REDIRECT_URL: ${{ secrets.REDIRECT_URL }}
      runs: 
        pip install virtualenv
        virtualenv venv
        source ./venv/bin/activate

        mkdir ~/.aws/
        echo "[perso]
        aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key = ${{ secrets.AWS_SECRET_KEY_ID }}
        region = eu-west-1" > ~/.aws/credentials
        cat ~/.aws/credentials
        echo '{
          "dev":{
              "app_function":"app.app",
              "profile_name":"perso",
              "project_name":"flask",
              "runtime":"python3.7",
              "s3_bucket":"zappa-5r36r8xuk",
              "environment_variables":{
                  "SPOTIFY_CLIENT_ID":"${{ secrets.SPOTIFY_CLIENT_ID }}",
                  "SPOTIFY_CLIENT_SECRET_ID":"${{ secrets.SPOTIFY_CLIENT_SECRET_ID }}",
                  "HOME_URL":"https://nzh8p1ckm8.execute-api.eu-west-1.amazonaws.com/dev",
                  "REDIRECT_URL":"https://nzh8p1ckm8.execute-api.eu-west-1.amazonaws.com/dev/get-token"
              }
          }
        }' > zappa_settings.json
        zappa update
